# Generated by Django 4.2.14 on 2024-07-18 22:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_application_info_alter_fellow_info_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presentation",
            old_name="content",
            new_name="summary",
        ),
        migrations.RenameField(
            model_name="testimonial",
            old_name="user",
            new_name="fellow",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="link",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="media",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="tags",
        ),
        migrations.AddField(
            model_name="application",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="applicant_pictures"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
        migrations.AddField(
            model_name="presentation",
            name="cohort",
            field=models.CharField(default=2024, max_length=255),
        ),
        migrations.AddField(
            model_name="presentation",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="presentations"),
        ),
        migrations.AddField(
            model_name="presentation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="presenter_pictures"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict, null=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="projects"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "fellow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="database.fellow",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(
                        related_name="projects", to="database.policysubtopic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
