# Generated by Django 4.2.14 on 2024-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_content_presentation_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='testimonials'),
        ),
    ]
