# Generated by Django 4.2.14 on 2024-07-21 09:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_remove_userprofile_bio_fellow_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTrip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict, null=True)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("cohort", models.CharField(default=2024, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="application",
            name="motivation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SiteTripImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("info", models.JSONField(blank=True, default=dict, null=True)),
                ("image", models.FileField(upload_to="site_trip_images")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="database.sitetrip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
