# Generated by Django 4.2.14 on 2024-07-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_sitetrip_application_motivation_sitetripimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellow',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='program',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='school',
        ),
        migrations.AlterField(
            model_name='fellow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.application'),
        ),
    ]
