SCHOOLS = [
    "University of Colorado Boulder",
    "Colorado State University",
    "University of Denver",
    "Colorado College",
    "Metropolitan State University of Denver",
    "Colorado School of Mines",
    "Regis University",
    "Adams State University",
    "Fort Lewis College",
    "Colorado Mesa University",
    "Western Colorado University",
    "University of Colorado Colorado Springs",
    "University of Northern Colorado",
    "Colorado Christian University",
    "Colorado Mountain College",
]